// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/k8snetworkplumbingwg/sriovnet/pkg/utils/docacaps"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDOCACaps creates a new instance of MockDOCACaps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDOCACaps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDOCACaps {
	mock := &MockDOCACaps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDOCACaps is an autogenerated mock type for the DOCACaps type
type MockDOCACaps struct {
	mock.Mock
}

type MockDOCACaps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDOCACaps) EXPECT() *MockDOCACaps_Expecter {
	return &MockDOCACaps_Expecter{mock: &_m.Mock}
}

// GetDocaCapRepDevByVUID provides a mock function for the type MockDOCACaps
func (_mock *MockDOCACaps) GetDocaCapRepDevByVUID(vuid string) (*docacaps.DocaCapRepDev, error) {
	ret := _mock.Called(vuid)

	if len(ret) == 0 {
		panic("no return value specified for GetDocaCapRepDevByVUID")
	}

	var r0 *docacaps.DocaCapRepDev
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*docacaps.DocaCapRepDev, error)); ok {
		return returnFunc(vuid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *docacaps.DocaCapRepDev); ok {
		r0 = returnFunc(vuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*docacaps.DocaCapRepDev)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(vuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDOCACaps_GetDocaCapRepDevByVUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocaCapRepDevByVUID'
type MockDOCACaps_GetDocaCapRepDevByVUID_Call struct {
	*mock.Call
}

// GetDocaCapRepDevByVUID is a helper method to define mock.On call
//   - vuid string
func (_e *MockDOCACaps_Expecter) GetDocaCapRepDevByVUID(vuid interface{}) *MockDOCACaps_GetDocaCapRepDevByVUID_Call {
	return &MockDOCACaps_GetDocaCapRepDevByVUID_Call{Call: _e.mock.On("GetDocaCapRepDevByVUID", vuid)}
}

func (_c *MockDOCACaps_GetDocaCapRepDevByVUID_Call) Run(run func(vuid string)) *MockDOCACaps_GetDocaCapRepDevByVUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDOCACaps_GetDocaCapRepDevByVUID_Call) Return(docaCapRepDev *docacaps.DocaCapRepDev, err error) *MockDOCACaps_GetDocaCapRepDevByVUID_Call {
	_c.Call.Return(docaCapRepDev, err)
	return _c
}

func (_c *MockDOCACaps_GetDocaCapRepDevByVUID_Call) RunAndReturn(run func(vuid string) (*docacaps.DocaCapRepDev, error)) *MockDOCACaps_GetDocaCapRepDevByVUID_Call {
	_c.Call.Return(run)
	return _c
}
